### PR TITLE
Refactor: Trim whitespace in input fields

### PR DESCRIPTION
**Pull request by stephdl**
This pull request refactors multiple components to trim whitespace in input fields.

The affected components are RuleEditor.vue, RuleCreator.vue, PolicyEditor.vue, PolicyCreator.vue, and MultiWanGeneralSettings.vue.

The whitespace trimming is done using the v-model.trim directive.

This improves the user experience by automatically removing leading and trailing whitespace from input values.

https://github.com/NethServer/nethsecurity/issues/580

### CODE REVIEW

**Comment by andre8244** [comment]
> Isn't better to trim these values in the backend? If someone calls the CLI with a space the issue will persist

You are right but I fear most (all?) of our APIs don't do any trim. A UI trim is the first layer of defense against bad user input and can probably cover 99% of the scenarios. That being said, IMO it would be a good idea to apply input trim in out future APIs.

**Review by andre8244 — APPROVED** [review]

**Review by gsanchietti — COMMENTED** [review]
Does mwan3 fail if these fields contains a space?

**Comment by stephdl** [comment]
image

**Comment by stephdl** [comment]
for the policy, the label got a space in its name, not sure it is good : `"name": "ns_foo2", "label": "foo2 "`

```
root@NethSec:~#  echo '{}' | /usr/libexec/rpcd/ns.mwan call index_policies
{"values": [{"name": "ns_default", "label": "Default", "members": {"10": [{"name": "ns_wan_M10_W100", "interface": "wan", "metric": "10", "weight": "100", "status": "online"}, {"name": "ns_wan2_M10_W100", "interface": "wan2", "metric": "10", "weight": "100", "status": "online"}]}, "type": "balance"}, {"name": "ns_foo2", "label": "foo2 ", "members": {"10": [{"name": "ns_wan_M10_W100", "interface": "wan", "metric": "10", "weight": "100", "status": "online"}, {"name": "ns_wan2_M10_W100", "interface": "wan2", "metric": "10", "weight": "100", "status": "online"}]}, "type": "balance"}]}
```

**Review by gsanchietti — APPROVED** [review]
OK, let's merge it but it seems to me that is not strictly needed.

**Pull request merged**
